/**
 *
 * $Id$
 */
package moon.nju.edu.cn.demo.validation;

import moon.nju.edu.cn.demo.Server;
import moon.nju.edu.cn.demo.Software;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link moon.nju.edu.cn.demo.Software}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SoftwareValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateVersion(String value);
	boolean validateServers(Server value);
	boolean validateDependOn(EList<Software> value);
	boolean validateCPU(int value);
	boolean validateMEM(int value);
}
