/**
 *
 * $Id$
 */
package moon.nju.edu.cn.demo.validation;

import moon.nju.edu.cn.demo.MySQL;

/**
 * A sample validator interface for {@link moon.nju.edu.cn.demo.WebApp}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WebAppValidator {
	boolean validate();

	boolean validateConnectTo(MySQL value);
}
